language: node_js
node_js:
- lts/*
jobs:
  include:
  - stage: test
    script:
    - yarn test
  - stage: deploy
    name: Deploy to heroku
    if: branch = develop || master
    before_deploy:
    - yarn build
    deploy:
      skip_cleanup: true
      provider: heroku
      app:
        master: character-dictionary
        develop: character-dictionary
      on:
        repo: salilkapoor/character_dictionary_assignment
        all_branches: true
      api_key:
        secure: gSKW4th29S+uKKhWWbhahlf5RMHNYGE8SthyFWGqIzZq69tzT333tPBGRzJ9q9sQUGSiB+aqRRSfd/jkJVa3/n2imQSilJ+khlK5s+Aq0B+SQE7n79cEVlpOyoM5wGyKEnB7CZRh8YEjWZdHwG5qBfYrx76Lv5iinor5lKvpxZwjZ85a5eS5dOxeKVAtRXZwLoXhylvfWlXgz3tQEiO3wj2yfM3e9xP8hX46DDkfsWWSCwtvlD54ZVzzcVBlVd/X2C6zCa8UlwCzJUb7O4511EKsS5cPXmh6iBfMLyvZoRGVp33904abTp9LOk9cqWyUP5HJwQi+OkR6D3wmc4gO4czcAEJgwnnqdp7NJM8faNMo86gO4gce2fF9x39tk3UuQxrbkYnizTFa53gr1soKieOcit3WmXWEpCq5klpTgsDFZ2+ViTG8y49QrPYL54469vLO5ZOubqJwoTrL+GyS+nYsEooPvdYZ0nZhKaBEo/JAP2r1ioEl+fpFF3+IN9lmEeG8Q2r/rPXQ89pYxaRgQIRfGvhOC763Xm0tbAZ08swItRAPpJf1QsbBc8s6IwKDPI5ZtWQlyEcP6mQmySsCuNa1HDDxOTxIKuRLUjbfXQ1zdEt+RIuOtJJV+zONxhJCfEGOPMNXrnU9fVFBktj8qyEnknjJ5FleHVswWh29gko=