language: node_js
node_js:
- lts/*
jobs:
  include:
  - stage: test
    script:
    - yarn test
  - stage: deploy
    name: Deploy to heroku
    if: branch = develop || master
    before_deploy:
    - yarn build
    deploy:
      skip_cleanup: true
      provider: heroku
      app:
        master: character-dictionary
        develop: character-dictionary
      on:
        repo: salilkapoor/character_dictionary_assignment
        all_branches: true
      api_key:
        secure: KueIMIaTKyZxlzSxkaGs0NzQNku1E7p2UgRsJwbQBUvJKY7Gi/kRR7OF3sUR/sxEFIMkkkCqy/hKFjrUqGTExtEIUj09cdanq5WpXNH4PIsYGJe6sr3jBW5gA4+t5H0lpjWpYD+n93ernVCYxiCPndyGmH5rHryD2zrau6Y1mqtCTkPOyuHZs4U/06Qg2hQxl6yh+iaDNC3fd0goHk/wPri2vKU6THVgM5e+L/oLTfyI1s4fZAqyIpfreqtKGs2lJLsCQO2tFa5KP+7ngK8nemjZUyFSZqxA7ArwTfAOCo5qW6Ig9GW0mR9e+sotR8IhiPp7NlfdYIP+ym13gN6qPNIqKPn2FPxcZW00ci7sEaFeEL6ymDw1+UlKqlmfCxib1OxaLT54/b+cwzNT5TFwjAKBrSOCLbG/XSF/3HU9w1hmHesdvFdhNKtgKb5m1KTWtvJULzlJCG5jr2u+O4KXtnV6pxkS8X6NJd0lK8ZHQwQ3bOs1UyONjYi8TwaxqVz7jeIGT+1lAyq3C3iMLPQ8PcP2fGqGloTPHSpYU/tyw2v9emE4IGYe+hYFNEqEzxCzVXqsTL5lKRQjsTaLBjin36P/t0ZNNrLb9eJX4yn1IHW9vNTh+UUZ3bkCZiE2Ac1sQjB+raUMrEItdi1U8iCXUiIAYE9bAO5DHg6zk0u43EA=