language: node_js
node_js:
- lts/*
jobs:
  include:
  - stage: test
    script:
    - yarn test
  - stage: deploy
    name: Deploy to heroku
    if: branch = master
    before_deploy:
    - yarn build
    deploy:
      skip_cleanup: true
      provider: heroku
      app:
        master: character-dictionary
      on:
        repo: salilkapoor/character_dictionary_assignment
        all_branches: true
      api_key:
        secure: lYcPdMsmz+eYeZWY6YAbZa2bMgRmX8LutZEf3KA/ofQk79JJXQz/WlMQRIj/l4C9lzHiZWTIUKLnylVXro8+wGlP1v8Vv1N2SYUZim/dBNF2onroCfvGP5uZRC95nlUbvN2+MfFWxy1rM7D/mdEqty9KVnUnqtv8fRC6xFhUwVPZL1CJ2beVLJORuvyH+jXb0bcRBMrCkwp29Lq6OKRL+X79LE5FTGf5dl4U0dYCwzMN/gxDymz3bwWUgBlXk35ZrlOSy4kx/in7qH5zw9ftEUdibpuFYPDsi7WzKsjN+gu37aabF5vAv0Fxb9DypFv/g1p5E/FcARwNEVykzUhMX/F385MPTEdykFHlPI+QnBAKxQNPiAfsxVeGJh7jvoChmYSip+82gOLywudXxRSQZMtCpwnXb37tAgZVJGFMz4aeWKImCI8rSeorpxwMNZcnyQueudZTsvITNPkv9jJCIVA6KL+w2ggljB6X6+2SCUz9lfY/ekZHKPMfyynoq8Y1HHfwsXVub6+WvL3Z5+x7K4RJIe1vUifND5N1bnAxamepnq8A8yQRpUxf79O+jzJsd9hOJLjiat5zwj5vYN819GHkGSh27lzET1fV/YkbACrRX16Nb75owWmxGJyt+kGVhRFiw1XThoNZPBnTIRs9tQFJO+tomfIP+6BAVVKarmM=