language: node_js
node_js:
- lts/*
jobs:
  include:
  - stage: test
    script:
    - yarn test
  - stage: deploy
    name: Deploy to heroku
    if: branch = master
    before_deploy:
    - yarn build
    deploy:
      skip_cleanup: true
      provider: heroku
      app:
        master: character-dictionary
      on:
        repo: salilkapoor/character_dictionary_assignment
        all_branches: true
      api_key:
        secure: ZnH4aY4v450aRVp08dNsZlJ0V6chEiYamWUF+jT2bjcyfgQCLxqWObG5aw+8wtkkrXf7JfyBsBVJ5/RXlrEvAGr605Fv7z6jXhknijeteopmuJoBEWDw7ar20XMNnIMOrBQWRJ5an2feAjE/gtXnkjoJIn0oIQZEYzVqzPZwBKTWFhlGjANZ6B6x+zoWNtKXr6AzcnK78eEzHTFcOD7wSzmX53NjTbQoy6tuekI5H9R28UWTwfZaHHKqgfHus6LosAPbtVOajyFeZ0Y5viJkprskBqnjllLynfpvCSaGjd3Qe2nWui+E3RUHLEGeJvCNhuOsDBAFBS379VFiCYg4hlRAM2dMT2ppjUbe0XwC9B4HE/G6AWutEc0yBt5NxyNyGjkCU7KJa0dcR3Z7ryeo/tCBJA+GzmkInmyS8TuzpN/WDvYI5zP9LitvPIgTVCzoOXAjXhF90BBreCR5Ut5qrPE+/nQnzhp+jlSv9YmQMZkllSfSalyHYOVYyH8Zmv55RHrZ+Ew2jfB6AA9Hj4E69UFGUv/HV27WOMh2Zpkgthp06slEFz7lYaVQxwV66TQnqfdg719Y+loiudrMZSprbDRe4kzomnGLZQtcat2FT3TutZNJFpZeNz38dOYiuaAlPX8xXxPFQ7awQGZe29ATnaLLgkl5jddsUbJtR2M1pi4=